#!/bin/bash

export ANSIBLE_HOST_KEY_CHECKING=False

if [[ -z ${ANSIBLE_SSH_KEY} ]]; then
    echo "No value specified for required environment variable: [ANSIBLE_SSH_KEY]"
    exit 1
fi

ansible-galaxy install -f -r ../ansible/requirements.yml || exit 1

ansible-playbook \
  --inventory inventory_aws_ec2.yml \
  --private-key ${ANSIBLE_SSH_KEY} \
  --extra-vars @variables.json \
  --diff \
  ../ansible/playbook.yml -v
