---
- name: Install Python dependencies
  pip:
    name: [
      'boto',
      'boto3',
      'botocore'
    ]
    umask: "0022"

# Create temporary directory for build artifacts
- name: Create temporary build directory
  tempfile:
    state: directory
  register: tempfile


- name: GET installer rpm from S3 bucket
  amazon.aws.aws_s3:
    bucket: "{{ resource_bucket_name }}"
    object: "{{ resource_bucket_artifactory_prefix }}/jfrog-artifactory-pro-{{ artifactory_version }}.rpm"
    dest: "/tempfile/jfrog-artifactory-pro-{{ artifactory_version }}.rpm"
    mode: get

- name: Install RPM package.
  yum:
    name: "/tempfile/jfrog-artifactory-pro-{{ artifactory_version }}.rpm"
    state: present

- name: Recursively remove directory
  ansible.builtin.file:
    path: /tempfile
    state: absent

- name: Stop the service
  service:
    name: artifactory
    state: stopped

- name: Disable the service
  service:
    name: artifactory
    enabled: no
