---
- name: Install LVM Tools
  ansible.builtin.dnf:
    name: lvm2
    state: latest

- name: Create artifactory_var_vg volume group
  community.general.lvg:
    vg: artifactory_var_vg
    state: present
    pvs:
      - "{{ artifactory_var_device_node }}"

- name: Create artifactory_var_lv logical volume
  community.general.lvol:
    lv: artifactory_var_lv
    vg: artifactory_var_vg
    resizefs: true
    size: +100%FREE
    state: present

- name: Create xfs filesystem on artifactory_var_lv
  community.general.filesystem:
    dev: /dev/mapper/artifactory_var_vg/artifactory_var_lv
    fstype: xfs
    state: present

- name: Create Artifactory var directory mount point
  ansible.builtin.file:
    path: "{{ artifactory_var_directory_path }}"
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Mount artifactory_var_lv to the mount point
  ansible.posix.mount:
    path: "{{ artifactory_var_directory_path }}"
    src: /dev/mapper/artifactory_var_vg-artifactory_var_lv
    fstype: xfs
    opts: defaults,noatime
    state: mounted

- name: Install Python pip
  ansible.builtin.dnf:
    name: "python3-pip"
    state: latest

- name: Install Python dependencies
  ansible.builtin.pip:
    name: [
      'boto',
      'boto3',
      'botocore'
    ]
    umask: "0022"

- name: Upgrade all packages
  ansible.builtin.dnf: 
    name: '*'
    state: latest

- name: Get Artifactory installer RPM from S3
  amazon.aws.s3_object:
    bucket: "{{ resource_bucket_name }}"
    object: "{{ resource_bucket_artifactory_prefix }}/{{ artifactory_package }}"
    dest: "/root/{{ artifactory_package }}"
    mode: get

- name: Install Artifactory RPM package
  ansible.builtin.dnf:
    name: "/root/{{ artifactory_package }}"
    disable_gpg_check: true
    state: present

- name: Remove Artifactory installer RPM
  ansible.builtin.file:
    path: "/root/{{ artifactory_package }}"
    state: absent

- name: Stop and disable the artifactory service
  ansible.builtin.service:
    name: artifactory
    enabled: no
    state: stopped

- name: Install EFS utils
  ansible.builtin.dnf:
    name: amazon-efs-utils
    state: latest

- name: Create the EFS directory
  ansible.builtin.file:
    path: /var/lib/artifactory
    state: directory

- name: Configure JFrog environment
  ansible.builtin.copy:
    mode: 0644
    owner: root
    group: root
    dest: "/etc/profile.d/artifactory.sh"
    content: |
      export JFROG_HOME="/opt/jfrog"
