---
- name: Install Python pip
  ansible.builtin.dnf:
    name: "python3-pip"
    state: latest

- name: Install Python dependencies
  ansible.builtin.pip:
    name: [
      'boto',
      'boto3',
      'botocore'
    ]
    umask: "0022"

- name: Upgrade all packages
  ansible.builtin.dnf: 
    name: '*'
    state: latest

- name: Reboot the server
  ansible.builtin.reboot:
    connect_timeout: 90
    post_reboot_delay: 90
    msg: "Reboot initiated by Ansible"

- name: Create temporary build directory to install artifactory
  ansible.builtin.tempfile:
    state: directory
  register: tempfile

- name: Get Artifactory installer rpm from S3 bucket
  amazon.aws.aws_s3:
    bucket: "{{ resource_bucket_name }}"
    object: "{{ resource_bucket_artifactory_prefix }}/{{ artifactory_package }}"
    dest: "{{ tempfile.path }}/{{ artifactory_package }}"
    mode: get

- name: Install Artifactory RPM package.
  ansible.builtin.dnf:
    name: "{{ tempfile.path }}/{{ artifactory_package }}"
    state: present

- name: Remove temporary artifactory build directory
  ansible.builtin.file:
    path: "{{ tempfile.path }}"
    state: absent

- name: Stop and disable the artifactory service
  ansible.builtin.service:
    name: artifactory
    enabled: no
    state: stopped

- name: install efs utils
  ansible.builtin.dnf:
    name: amazon-efs-utils
    state: latest

- name: Configure JFrog environment
  ansible.builtin.copy:
    mode: 0644
    owner: root
    group: root
    dest: "/etc/profile.d/artifactory.sh"
    content: |
      export JFROG_HOME="/opt/jfrog"

- name: Enable compress for logrotate syslog configuration
  ansible.builtin.lineinfile:
    path: "/etc/logrotate.d/syslog"
    insertafter: 'sharedscripts'
    line: '    compress'

- name: Create the EFS directory
  ansible.builtin.file:
    path: /var/lib/artifactory
    state: directory
