---
- name: Install Python dependencies
  pip:
    name: [
      'boto',
      'boto3',
      'botocore'
    ]
    umask: "0022"

- name: upgrade all packages
  yum: 
    name: '*'
    state: latest

- name: Reboot the server
  reboot:
    connect_timeout: 90
    post_reboot_delay: 90
    msg: "Reboot initiated by Ansible"

- name: Create temporary build directory to install artifactory
  tempfile:
    state: directory
  register: tempfile

- name: GET Artifactory installer rpm from S3 bucket
  amazon.aws.aws_s3:
    bucket: "{{ resource_bucket_name }}"
    object: "{{ resource_bucket_artifactory_prefix }}/{{ artifactory_package }}"
    dest: "{{ tempfile.path }}/{{ artifactory_package }}"
    mode: get

- name: Install Artifactory RPM package.
  yum:
    name: "{{ tempfile.path }}/{{ artifactory_package }}"
    state: present

- name: Remove temporary artifactory build directory
  ansible.builtin.file:
    path: "{{ tempfile.path }}"
    state: absent

- name: Stop the artifactory service
  service:
    name: artifactory
    state: stopped

- name: Disable the artifactory service
  service:
    name: artifactory
    enabled: no

- name: install EPEL
  yum:
    name: epel-release
    state: latest

- name: install efs utils
  yum:
    name: amazon-efs-utils
    state: latest

- name: Configure JFrog environment
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/etc/profile.d/artifactory.sh"
    content: |
      export JFROG_HOME="/opt/jfrog"

- name: Enable compress for logrotate syslog configuration
  ansible.builtin.lineinfile:
    path: "/etc/logrotate.d/syslog"
    insertafter: 'sharedscripts'
    line: 'compress'

- name: Create the EFS directory if it does not exist
  ansible.builtin.file:
    path: "/var/lib/artifactory"
    state: directory
